export const GET_RATES = 'GET_RATES';
export const SET_RATES = 'SET_RATES';

export const GET_POCKETS = 'GET_POCKETS';
export const SET_POCKETS = 'SET_POCKETS';

export const SET_POCKET_FROM = 'SET_POCKET_FROM';
export const SET_POCKET_TO = 'SET_POCKET_TO';

export const CHANGE_POCKETS = 'CHANGE_POCKETS';

export const CHANGE_WRITE_OFF_VALUE = 'CHANGE_WRITE_OFF_VALUE';
export const CHANGE_RECEIVE_VALUE = 'CHANGE_RECEIVE_VALUE';

export const DROP_EXCHANGE_VALUES = 'DROP_EXCHANGE_VALUES';

export const SET_WRITE_OFF_VALUE = 'SET_WRITE_OFF_VALUE';
export const SET_RECEIVE_VALUE = 'SET_RECEIVE_VALUE';

export const EXCHANGE = 'EXCHANGE';
